"""empty message

Revision ID: 558cc601510a
Revises: b2a730021d13
Create Date: 2016-12-21 15:45:10.305903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558cc601510a'
down_revision = 'b2a730021d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('cacademy', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('ccode', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('cetime', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('chour', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('cmargin', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('cproperty', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('cquantity', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('credit', sa.Float(), nullable=True))
    op.add_column('classes', sa.Column('croom', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('csource', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('ctime', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('cweek', sa.String(), nullable=True))
    op.add_column('classes', sa.Column('tname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'tname')
    op.drop_column('classes', 'cweek')
    op.drop_column('classes', 'ctime')
    op.drop_column('classes', 'csource')
    op.drop_column('classes', 'croom')
    op.drop_column('classes', 'credit')
    op.drop_column('classes', 'cquantity')
    op.drop_column('classes', 'cproperty')
    op.drop_column('classes', 'cmargin')
    op.drop_column('classes', 'chour')
    op.drop_column('classes', 'cetime')
    op.drop_column('classes', 'ccode')
    op.drop_column('classes', 'cacademy')
    # ### end Alembic commands ###
